apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: dapr-postgresql-state
  namespace: default
spec:
  type: state.postgresql
  version: v1
  metadata:
  - name: connectionString
    value: "<CONNECTION STRING>"

